name: note_engineer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.5+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.5.0
  supabase_flutter: ^2.5.8
  http: ^1.2.1
  path_provider: ^2.1.3
  provider:
  flutter_colorpicker: ^1.1.0
  file_picker: ^8.0.3
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  shared_preferences:
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2
  pointycastle: ^3.9.1
  easy_localization: ^3.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - .env